title: Max Logaev's blog
description: "Max Logaev's blog"
author:
  name: "mxlgv"
  email: "maxlogaev@proton.me"
  url: "https://mxlgv.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "mxlgv"
year : "2024"
